# -*- coding: utf-8 -*-
"""Fuel_Efficency_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iftGWzdtkOY-nN4ctM9lVLJ8k8fcE3EW
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("Fuel_Efiiciency_model.pkl")
encoder = joblib.load("label_encoder.pkl")

st.title("Fuel Efficiency Prediction App")

mpg = st.number_input("Enter MPG value")
cylinders = st.number_input("Enter Cylinders value")
displacement = st.number_input("Enter Displacement value")
horsepower = st.number_input("Enter Horsepower value")
weight = st.number_input("Enter Weight value")
acceleration = st.number_input("Enter Acceleration value")
model_year = st.number_input("Enter Model Year value")
origin = st.number_input("Enter Origin value")
car_name = st.text_input("Enter Car Name")

df = pd.DataFrame({
    "mpg": [mpg],
    "cylinders": [cylinders],
    "displacement": [displacement],
    "horsepower": [horsepower],
    "weight": [weight],
    "acceleration": [acceleration],
    "model year": [model_year],
    "origin": [origin],
    "car name": [car_name]
})

if st.button("Predict"):


    if isinstance(encoder, dict):
        for col in encoder:
            df[col] = encoder[col].transform(df[col])
    else:
        df["car name"] = encoder.transform(df["car name"])

    df = df[model.feature_names_in_]

    prediction = model.predict(df)

    st.success(f"Predicted fuel efficiency: {prediction[0]:,.2f}")